baseURL = "http://selbydavid.com/"
languageCode = "en-GB"
title = "Tea & Stats"
theme = "hugo-tea"
canonifyUrls = true
googleAnalytics = "UA-11136457-6"
disqusShortname = "tea-stats"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
  post = "/:year/:month/:day/:slug/"

[[menu.main]]
  name = "About"
  url = "/about/"

[author]
	name = "David Selby"
	url = "http://selbydavid.com"

[social]
	twitter 		= "TeaStats"
	facebook 		= "Selbosh"
	googleplus 	= "DavidASelby"
	github 			= "Selbosh"
  linkedin 		= "daselby"

[params]
	description = "Tea, statistics and t-statistics: a data science blog by David Selby."
  tagline = "Data science with David Selby"

  # Enable Font Awesome social icons.
  # Go to http://fontawesome.io/get-started/
  # and enter the ".js" URL you are sent in the embed code via e-mail
  fontawesome = "https://use.fontawesome.com/269c7751ba.js"

  # options for highlight.js (version, additional languages, and theme)
  highlightjsVersion = "9.11.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml"]
  highlightjsTheme = "github"

  MathJaxCDN = "//cdn.bootcss.com"
  MathJaxVersion = "2.7.1"

  [params.logo]
  url = "logo.png"
  rss = "logo.png" # should be png, gif or jpeg
  width = 120
  height = ""
  alt = "Tea and Stats"

  [params.footerimage]
  url = "logo.svg"
  width = 60
  height = ""
