# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Hugo Tea"
license = "MIT"
licenselink = "https://github.com/Selbosh/hugo-tea/blob/master/LICENSE.md"
description = ""
homepage = "http://siteforthistheme.com/"
tags = []
features = [blog, minimal]
min_version = "0.20.7"

[author]
  name = "David Selby"
  homepage = "http://selbydavid.com"
